PATCH /api/2.0/tenders/caad313da9e94222a6d68e70160927f7/awards/ff6378da400743a3b05dfef98f44ba26/complaints/85d9c6f3d07543bea1132d4961ddd4c7 HTTP/1.0
Authorization: Basic cmV2aWV3ZXI6
Content-Length: 32
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "accepted"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "accepted", 
    "documents": [
      {
        "author": "complaint_owner", 
        "title": "Complaint_Attachement.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.0/tenders/caad313da9e94222a6d68e70160927f7/awards/ff6378da400743a3b05dfef98f44ba26/complaints/85d9c6f3d07543bea1132d4961ddd4c7/documents/9d68edb3392447a68658e917bbb109ec?download=c78aedb267df403b8e9f93a53af60b93", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-03-16T14:33:25.608908+02:00", 
        "id": "9d68edb3392447a68658e917bbb109ec", 
        "dateModified": "2016-03-16T14:33:25.609006+02:00"
      }
    ], 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "title": "Недостатньо інформації", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
        "id": "13313462", 
        "uri": "http://sch10.edu.vn.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "dateAccepted": "2016-03-16T14:33:26.804585+02:00", 
    "dateSubmitted": "2016-03-16T14:33:25.847264+02:00", 
    "complaintID": "UA-2016-03-16-000001.1", 
    "date": "2016-03-16T14:33:25.413323+02:00", 
    "acceptance": true, 
    "type": "complaint", 
    "id": "85d9c6f3d07543bea1132d4961ddd4c7"
  }
}

