POST /api/2.0/tenders/12e5ee11241142dc9230c9b3d0c526c6/cancellations?acc_token=007f64e22bef4c08889c42d829806b0e HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 43
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "reason": "cancellation reason"
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.0/tenders/12e5ee11241142dc9230c9b3d0c526c6/cancellations/2f50781a4539468caf133174bf26194f
{
  "data": {
    "date": "2016-03-16T15:04:09.403199+02:00", 
    "status": "pending", 
    "reason": "cancellation reason", 
    "cancellationOf": "tender", 
    "id": "2f50781a4539468caf133174bf26194f"
  }
}

