PATCH /api/2.0/tenders/65340bb5ec1f43baade4f41f0c8f85c5/awards/c96d34aed32a4d0e83274ea6a417a2e6?acc_token=43d53a2143364495a211c142bd936b1c HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 30
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "active"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "complaintPeriod": {
      "startDate": "2016-03-16T14:33:31.805419+02:00", 
      "endDate": "2016-03-21T14:33:31.991421+02:00"
    }, 
    "suppliers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 475000.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2016-03-16T14:33:31.800017+02:00", 
    "id": "c96d34aed32a4d0e83274ea6a417a2e6"
  }
}

