PATCH /api/2.0/tenders/7d322198810f459193daa6b83c38582d/contracts/aca8d47cf00f473d8954e5431e2f095b?acc_token=6bcf8662fce14fd7aaad57c968dbd57a HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 36
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "value": {
      "amount": 238
    }
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "pending", 
    "items": [
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "CPV", 
          "description": "Послуги з харчування у школах", 
          "id": "55523100-3"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "55.51.10.300", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "id": "2dc54675d6364e2baffbc0f8e74432ac", 
        "unit": {
          "code": "MON", 
          "name": "month"
        }, 
        "quantity": 9
      }
    ], 
    "suppliers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 238.0, 
      "valueAddedTaxIncluded": true
    }, 
    "awardID": "1d5177955a794dcf9ddc1c5412768550", 
    "id": "aca8d47cf00f473d8954e5431e2f095b", 
    "contractID": "UA-2016-03-16-000001-1"
  }
}

