PATCH /api/2.0/tenders/eec4c788007f427db7d22eef1456a66b/awards/e6a3a3004c8443d19d2737f8e870c453?acc_token=ab7c4127081c41028a399c9c78308e9a HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 30
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "active"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "complaintPeriod": {
      "startDate": "2016-03-16T15:04:23.339615+02:00", 
      "endDate": "2016-03-21T15:04:23.555976+02:00"
    }, 
    "suppliers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 475000.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2016-03-16T15:04:23.338227+02:00", 
    "id": "e6a3a3004c8443d19d2737f8e870c453"
  }
}

