PATCH /api/2.0/tenders/12e5ee11241142dc9230c9b3d0c526c6/contracts/a7e14e8495a8459695d590a8191627ec?acc_token=007f64e22bef4c08889c42d829806b0e HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 30
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "active"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "documents": [
      {
        "title": "contract_first_document.doc", 
        "url": "http://api-sandbox.openprocurement.org/api/2.0/tenders/12e5ee11241142dc9230c9b3d0c526c6/contracts/a7e14e8495a8459695d590a8191627ec/documents/5226c3b87d404eb39a01a0db2db22a13?download=5cd493041a5d48e89105d23b2ebbe5dd", 
        "format": "application/msword", 
        "documentOf": "tender", 
        "datePublished": "2016-03-16T15:04:08.314379+02:00", 
        "id": "5226c3b87d404eb39a01a0db2db22a13", 
        "dateModified": "2016-03-16T15:04:08.314419+02:00"
      }, 
      {
        "title": "contract_second_document.doc", 
        "url": "http://api-sandbox.openprocurement.org/api/2.0/tenders/12e5ee11241142dc9230c9b3d0c526c6/contracts/a7e14e8495a8459695d590a8191627ec/documents/ea137e97f43943c9975a80d15fa10a9c?download=c134d0d249fc453b8b5835d11b63f073", 
        "format": "application/msword", 
        "documentOf": "tender", 
        "datePublished": "2016-03-16T15:04:08.627146+02:00", 
        "id": "ea137e97f43943c9975a80d15fa10a9c", 
        "dateModified": "2016-03-16T15:04:08.627186+02:00"
      }
    ], 
    "items": [
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "CPV", 
          "description": "Послуги з харчування у школах", 
          "id": "55523100-3"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "55.51.10.300", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "id": "2dc54675d6364e2baffbc0f8e74432ac", 
        "unit": {
          "code": "MON", 
          "name": "month"
        }, 
        "quantity": 9
      }
    ], 
    "suppliers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "period": {
      "startDate": "2016-03-16T15:04:07.981263+02:00", 
      "endDate": "2017-03-16T15:04:07.981320+02:00"
    }, 
    "value": {
      "currency": "UAH", 
      "amount": 238.0, 
      "valueAddedTaxIncluded": true
    }, 
    "dateSigned": "2016-03-16T15:04:07.748110+02:00", 
    "awardID": "f208403a2d5a4993874eedee17e12ab3", 
    "id": "a7e14e8495a8459695d590a8191627ec", 
    "contractID": "UA-2016-03-16-000001-1"
  }
}

