PATCH /api/2.0/tenders/4d12e387528c4e6dae9943f80282931e/contracts/f40b6e124b6a48179a70576cbbef32b8?acc_token=43021f76852b4959addf56f08219257c HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 30
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "active"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "items": [
      {
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "55.51.10.300", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "id": "2dc54675d6364e2baffbc0f8e74432ac", 
        "classification": {
          "scheme": "CPV", 
          "description": "Послуги з харчування у школах", 
          "id": "55523100-3"
        }, 
        "description": "Послуги шкільних їдалень"
      }
    ], 
    "suppliers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 475000.0, 
      "valueAddedTaxIncluded": true
    }, 
    "awardID": "893aeec019d948839729b6c410b588af", 
    "id": "f40b6e124b6a48179a70576cbbef32b8", 
    "contractID": "UA-2016-03-16-000001-1"
  }
}

