PATCH /api/2.0/tenders/7d322198810f459193daa6b83c38582d/contracts/aca8d47cf00f473d8954e5431e2f095b?acc_token=6bcf8662fce14fd7aaad57c968dbd57a HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 30
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "active"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "documents": [
      {
        "title": "contract_first_document.doc", 
        "url": "http://api-sandbox.openprocurement.org/api/2.0/tenders/7d322198810f459193daa6b83c38582d/contracts/aca8d47cf00f473d8954e5431e2f095b/documents/0184ed1beb3f4d03ba1e4be045b7672a?download=afbda26c3fc24e3a9ac129db7d4c45ba", 
        "format": "application/msword", 
        "documentOf": "tender", 
        "datePublished": "2016-03-16T13:04:44.132196+02:00", 
        "id": "0184ed1beb3f4d03ba1e4be045b7672a", 
        "dateModified": "2016-03-16T13:04:44.132238+02:00"
      }, 
      {
        "title": "contract_second_document.doc", 
        "url": "http://api-sandbox.openprocurement.org/api/2.0/tenders/7d322198810f459193daa6b83c38582d/contracts/aca8d47cf00f473d8954e5431e2f095b/documents/6565cfe6da98420185ca94405c641db0?download=466cf68f4d6b4303aa2520d47fcc8f19", 
        "format": "application/msword", 
        "documentOf": "tender", 
        "datePublished": "2016-03-16T13:04:44.444132+02:00", 
        "id": "6565cfe6da98420185ca94405c641db0", 
        "dateModified": "2016-03-16T13:04:44.444173+02:00"
      }
    ], 
    "items": [
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "CPV", 
          "description": "Послуги з харчування у школах", 
          "id": "55523100-3"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "55.51.10.300", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "id": "2dc54675d6364e2baffbc0f8e74432ac", 
        "unit": {
          "code": "MON", 
          "name": "month"
        }, 
        "quantity": 9
      }
    ], 
    "suppliers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 238.0, 
      "valueAddedTaxIncluded": true
    }, 
    "awardID": "1d5177955a794dcf9ddc1c5412768550", 
    "id": "aca8d47cf00f473d8954e5431e2f095b", 
    "contractID": "UA-2016-03-16-000001-1"
  }
}

