PATCH /api/2.0/tenders/12e5ee11241142dc9230c9b3d0c526c6/awards/f208403a2d5a4993874eedee17e12ab3?acc_token=007f64e22bef4c08889c42d829806b0e HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 30
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "active"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "documents": [
      {
        "title": "award_first_document.doc", 
        "url": "http://api-sandbox.openprocurement.org/api/2.0/tenders/12e5ee11241142dc9230c9b3d0c526c6/awards/f208403a2d5a4993874eedee17e12ab3/documents/f1466fc064fd45218e5fe560d054c6cf?download=7d9d05b04b0d45c5a2770addbd780133", 
        "format": "application/msword", 
        "documentOf": "tender", 
        "datePublished": "2016-03-16T15:04:06.901075+02:00", 
        "id": "f1466fc064fd45218e5fe560d054c6cf", 
        "dateModified": "2016-03-16T15:04:06.901115+02:00"
      }, 
      {
        "title": "award_second_document.doc", 
        "url": "http://api-sandbox.openprocurement.org/api/2.0/tenders/12e5ee11241142dc9230c9b3d0c526c6/awards/f208403a2d5a4993874eedee17e12ab3/documents/4d144d2bddfd4dacaddb99fea85f12de?download=fbea8b9a306e41798fca3d9a2a2f69e4", 
        "format": "application/msword", 
        "documentOf": "tender", 
        "datePublished": "2016-03-16T15:04:07.140774+02:00", 
        "id": "4d144d2bddfd4dacaddb99fea85f12de", 
        "dateModified": "2016-03-16T15:04:07.140813+02:00"
      }
    ], 
    "suppliers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 475000.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2016-03-16T15:04:06.682607+02:00", 
    "id": "f208403a2d5a4993874eedee17e12ab3"
  }
}

