PATCH /api/2.0/tenders/278d33d925b0479f83c3ba428713d834/awards/dc50dc2dc16b4a4ab1452c0d6ebdd4ca?acc_token=120eb9e302d3413cbd3aaf6ec8347283 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 30
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "active"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "documents": [
      {
        "title": "award_first_document.doc", 
        "url": "http://api-sandbox.openprocurement.org/api/2.0/tenders/278d33d925b0479f83c3ba428713d834/awards/dc50dc2dc16b4a4ab1452c0d6ebdd4ca/documents/7e1e8d8756de4af79256c62a5dca07d2?download=3eafe19e470148a8b9190e5831483cae", 
        "format": "application/msword", 
        "documentOf": "tender", 
        "datePublished": "2016-03-16T14:33:15.516218+02:00", 
        "id": "7e1e8d8756de4af79256c62a5dca07d2", 
        "dateModified": "2016-03-16T14:33:15.516258+02:00"
      }, 
      {
        "title": "award_second_document.doc", 
        "url": "http://api-sandbox.openprocurement.org/api/2.0/tenders/278d33d925b0479f83c3ba428713d834/awards/dc50dc2dc16b4a4ab1452c0d6ebdd4ca/documents/3ac1c893449e4c7394ce02991144732b?download=c0400e022fb24998a2fe4eb13bade3bf", 
        "format": "application/msword", 
        "documentOf": "tender", 
        "datePublished": "2016-03-16T14:33:15.766117+02:00", 
        "id": "3ac1c893449e4c7394ce02991144732b", 
        "dateModified": "2016-03-16T14:33:15.766155+02:00"
      }
    ], 
    "suppliers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 475000.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2016-03-16T14:33:15.283249+02:00", 
    "id": "dc50dc2dc16b4a4ab1452c0d6ebdd4ca"
  }
}

