GET /api/2.0/tenders?opt_pretty=1 HTTP/1.0
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "next_page": {
    "path": "/api/2.0/tenders?offset=2016-03-16T15%3A04%3A05.933874%2B02%3A00", 
    "uri": "http://api-sandbox.openprocurement.org/api/2.0/tenders?offset=2016-03-16T15%3A04%3A05.933874%2B02%3A00", 
    "offset": "2016-03-16T15:04:05.933874+02:00"
  }, 
  "data": [
    {
      "id": "12e5ee11241142dc9230c9b3d0c526c6", 
      "dateModified": "2016-03-16T15:04:05.933874+02:00"
    }
  ]
}

