PATCH /api/2.0/tenders/278d33d925b0479f83c3ba428713d834/contracts/fd2c4d5f8562472ea3f937384b4ef10c?acc_token=120eb9e302d3413cbd3aaf6ec8347283 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 30
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "active"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "documents": [
      {
        "title": "contract_first_document.doc", 
        "url": "http://api-sandbox.openprocurement.org/api/2.0/tenders/278d33d925b0479f83c3ba428713d834/contracts/fd2c4d5f8562472ea3f937384b4ef10c/documents/2f9243d6c3884dff92647b7498f05854?download=0a2dd6494c0843bc8d1a7dd61c4e4d7c", 
        "format": "application/msword", 
        "documentOf": "tender", 
        "datePublished": "2016-03-16T14:33:16.708030+02:00", 
        "id": "2f9243d6c3884dff92647b7498f05854", 
        "dateModified": "2016-03-16T14:33:16.708070+02:00"
      }, 
      {
        "title": "contract_second_document.doc", 
        "url": "http://api-sandbox.openprocurement.org/api/2.0/tenders/278d33d925b0479f83c3ba428713d834/contracts/fd2c4d5f8562472ea3f937384b4ef10c/documents/931f7a537d1f4b42b805968a8fce545e?download=56ecc253feb14490b480f9b4e3f97d21", 
        "format": "application/msword", 
        "documentOf": "tender", 
        "datePublished": "2016-03-16T14:33:16.990382+02:00", 
        "id": "931f7a537d1f4b42b805968a8fce545e", 
        "dateModified": "2016-03-16T14:33:16.990422+02:00"
      }
    ], 
    "items": [
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "CPV", 
          "description": "Послуги з харчування у школах", 
          "id": "55523100-3"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "55.51.10.300", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "id": "2dc54675d6364e2baffbc0f8e74432ac", 
        "unit": {
          "code": "MON", 
          "name": "month"
        }, 
        "quantity": 9
      }
    ], 
    "suppliers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 238.0, 
      "valueAddedTaxIncluded": true
    }, 
    "dateSigned": "2016-03-16T14:33:16.370519+02:00", 
    "awardID": "dc50dc2dc16b4a4ab1452c0d6ebdd4ca", 
    "id": "fd2c4d5f8562472ea3f937384b4ef10c", 
    "contractID": "UA-2016-03-16-000001-1"
  }
}

