POST /api/2.0/tenders/278d33d925b0479f83c3ba428713d834/documents?acc_token=120eb9e302d3413cbd3aaf6ec8347283 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 184
Content-Type: multipart/form-data; boundary=----------a_BoUnDaRy98150107985$
Host: api-sandbox.openprocurement.org

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.0/tenders/278d33d925b0479f83c3ba428713d834/documents/3eda28af72514ab2a67ea3ca9f1bcb44
{
  "data": {
    "title": "Notice.pdf", 
    "url": "http://api-sandbox.openprocurement.org/api/2.0/tenders/278d33d925b0479f83c3ba428713d834/documents/3eda28af72514ab2a67ea3ca9f1bcb44?download=a47be0109ec94095bce84452513ff9c8", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2016-03-16T14:33:14.868088+02:00", 
    "id": "3eda28af72514ab2a67ea3ca9f1bcb44", 
    "dateModified": "2016-03-16T14:33:14.868127+02:00"
  }
}

